In [4]:
print("hello world")

hello world


In [ ]:
print("hello world from mac")

In [1]:
import torch

# Create an empty tensor
tensor = torch.zeros(3, 5)

# Index tensor
index = torch.tensor([[0, 0, 0, 0, 1],
                      [3, 0, 0, 0, 0],
                      [2, 0, 1, 1, 2]])

In [5]:
torch.cuda.is_available()

True

In [6]:
torch.cuda.device_count()

1

In [13]:
torch.cuda.set_device(0)

In [11]:
torch.device("cpu")

device(type='cpu')

In [14]:
torch.device("cuda")

device(type='cuda')

In [18]:
torch.tensor([0])

tensor([0])

In [21]:
torch.tensor([0]).to(torch.device("cpu"))

tensor([0])

In [19]:
torch.tensor([0]).to(torch.device("cuda"))

tensor([0], device='cuda:0')

In [28]:
torch.tensor([0, 1, 2]).to(torch.device("cuda")) * 10

tensor([ 0, 10, 20], device='cuda:0')

In [29]:
torch.tensor([0, 1, 2]).to(torch.device("cuda")) * torch.tensor([10])

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [23]:
torch.tensor([0, 1, 2]).to(torch.device("cuda")) * torch.tensor([0]).to(torch.device("cpu"))

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [32]:
torch.tensor([0]).cuda(0)

tensor([0], device='cuda:0')

In [33]:
test_tensor = torch.tensor([0])

In [40]:
test_tensor2 = torch.tensor([0], device=device)

In [41]:
test_tensor2

tensor([0], device='cuda:0')

In [44]:
src = torch.tensor([0], device = device)

In [34]:
test_tensor

tensor([0])

In [36]:
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")

In [37]:
device

device(type='cuda')

In [38]:
test_tensor.to(device)

tensor([0], device='cuda:0')

In [39]:
test_tensor

tensor([0])

In [2]:
src = torch.tensor([[1, 2, 3, 4, 5],
                    [6, 7, 8, 9, 10],
                    [11, 12, 13, 14, 15]])

In [30]:
tensor.scatter_(1, index, 1)

tensor([[1., 1., 0., 0., 0.],
        [1., 0., 0., 1., 0.],
        [1., 1., 1., 0., 0.]])

In [46]:
# Indices to be one-hot encoded
indices = torch.tensor([0, 2, 1, 3])

# Number of classes
num_classes = 5

# Create a zero tensor for one-hot encoding
one_hot = torch.zeros(indices.size(0), num_classes)


In [47]:
one_hot

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [48]:
indices.unsqueeze(1)

tensor([[0],
        [2],
        [1],
        [3]])

In [49]:
# One-hot encode using scatter_
one_hot.scatter_(1, indices.unsqueeze(1), 1)

print(one_hot)

tensor([[1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.]])


In [50]:
one_hot

tensor([[1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.]])

In [58]:
one_hot[:, -1]

tensor([0., 0., 0., 0.])

In [51]:
one_hot.view(-1)

tensor([1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        1., 0.])

In [60]:
one_hot

tensor([[1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.]])

In [59]:
one_hot.data

tensor([[1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.]])

In [52]:
import math

In [53]:
 math.sqrt(2).move

1.4142135623730951

In [54]:
tensor.sqrt(2)

TypeError: _TensorBase.sqrt() takes no arguments (1 given)